service: s3-file-uploader

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

custom:
  fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::BUCKET
      Properties:
        BucketName: ${self:service}-bucket-${self:provider.stage}
        AccessControl: PublicRead
